version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: lab2/Dockerfile
    container_name: ${APP_CONTAINER_NAME}
    ports:
      - "${APP_PORT}:8000"
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
    depends_on:
      db:
        condition: service_healthy
      init_service:
        condition: service_completed_successfully
    networks:
      - main_net
    command: ["uvicorn", "lab2.main:app", "--host", "0.0.0.0", "--port", "8000"]

  db:
    image: redis:alpine
    container_name: ${DB_CONTAINER_NAME}
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - main_net

  init_service:
    image: busybox
    container_name: ${INIT_CONTAINER_NAME}
    command: sh -c "echo 'Performing initialization tasks...'; sleep 5; echo 'Initialization complete.'"
    networks:
      - main_net

volumes:
  redis_data:

networks:
  main_net:
    name: ${NETWORK_NAME}
